language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t diiegg/multi-docker1 -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true diiegg/multi-docker1 npm test

after_success:
  - docker build -t diiegg/multi-client ./client
  - docker build -t diiegg/multi-nginx ./nginx
  - docker build -t diiegg/multi-server ./server
  - docker build -t diiegg/multi-worker ./worker

  #log in docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
  - docker push diiegg/multi-client
  - docker push diiegg/multi-nginx
  - docker push diiegg/multi-server
  - docker push diiegg/multi-worker